import { useEffect, useState } from "react";
import { ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, Tooltip, CartesianGrid, Legend } from "recharts";
import api from "../api/client"; import Badge from "../components/Badge";
const COLORS=["#4f46e5","#12b76a","#2e90fa","#f79009","#7f56d9","#f04438"];
export default function Dashboard(){
 const [stats,setStats]=useState(null),[monthly,setMonthly]=useState([]),[statusBreakdown,setStatusBreakdown]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{async function load(){try{const [s,m,b]=await Promise.all([api.get("/dashboard/stats"),api.get("/dashboard/monthly?months=6"),api.get("/dashboard/order-status-breakdown")]);setStats(s.data);setMonthly(m.data);setStatusBreakdown(b.data)}finally{setLoading(false)}}load()},[]);
 if(loading||!stats)return <div className="empty-state">Loading your business dashboard…</div>;
 const money=n=>`₹${Number(n).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
 const cards=[["◉","Total Customers",stats.total_customers,"primary"],["▣","Total Products",stats.total_products,"primary"],["□","Total Orders",stats.total_orders,"primary"],["₹","Total Sales",money(stats.total_sales),"success"],["−","Total Expenses",money(stats.total_expenses),"danger"],["↗","Total Profit",money(stats.total_profit),"success"],["◷","Pending Payments",money(stats.pending_payments),"warning"]];
 return <div><div className="hero-banner"><div className="hero-copy"><div className="eyebrow">Business overview</div><h2>Good to see you back</h2><p>Here’s what’s happening across your business today. Need a quick answer? Ask the assistant in the corner.</p><button className="btn btn-primary" onClick={()=>window.location.href="/orders"}>＋ New Order</button></div><img src="/images/dashboard-banner.svg" alt="" className="hero-img"/></div>
  <div className="stat-grid">{cards.map(([icon,label,value,tone])=><div className="stat-card" key={label}><div className="stat-top"><div className="label">{label}</div><div className={`stat-icon tone-${tone}`}>{icon}</div></div><div className="value">{value}</div><div className="stat-change"><span className="positive">●</span> Live business data</div></div>)}</div>
  <div className="chart-grid"><div className="card chart-card"><div className="card-title"><h3>Revenue performance</h3><span>Last 6 months</span></div><ResponsiveContainer width="100%" height={275}><LineChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#eaecf0"/><XAxis dataKey="month" fontSize={11} axisLine={false} tickLine={false}/><YAxis fontSize={11} axisLine={false} tickLine={false}/><Tooltip formatter={v=>money(v)} contentStyle={{borderRadius:10,border:"1px solid #e4e7ec"}}/><Legend/><Line type="monotone" dataKey="sales" stroke="#4f46e5" strokeWidth={3} dot={false}/><Line type="monotone" dataKey="expenses" stroke="#f04438" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="profit" stroke="#12b76a" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer></div>
   <div className="card chart-card"><div className="card-title"><h3>Order status</h3><span>Current</span></div><ResponsiveContainer width="100%" height={275}><PieChart><Pie data={statusBreakdown} dataKey="count" nameKey="status" innerRadius={58} outerRadius={88} paddingAngle={3}>{statusBreakdown.map((_,i)=><Cell key={i} fill={COLORS[i%COLORS.length]}/>)}</Pie><Tooltip/><Legend iconType="circle"/></PieChart></ResponsiveContainer></div></div>
  <div className="chart-grid"><div className="card"><div className="card-title"><h3>Recent orders</h3><span>{stats.recent_orders.length} latest</span></div><div className="table-wrap" style={{border:"none",boxShadow:"none"}}><table><thead><tr><th>ID</th><th>Customer</th><th>Total</th><th>Status</th></tr></thead><tbody>{stats.recent_orders.length===0?<tr><td colSpan={4} className="empty-state">No orders yet</td></tr>:stats.recent_orders.map(o=><tr key={o.id}><td>#{o.id}</td><td>{o.customer_name}</td><td>{money(o.total_amount)}</td><td><Badge value={o.status}/></td></tr>)}</tbody></table></div></div>
   <div className="card"><div className="card-title"><h3>Recent payments</h3><span>Latest activity</span></div><div className="table-wrap" style={{border:"none",boxShadow:"none"}}><table><thead><tr><th>ID</th><th>Customer</th><th>Amount</th><th>Method</th></tr></thead><tbody>{stats.recent_payments.length===0?<tr><td colSpan={4} className="empty-state">No payments yet</td></tr>:stats.recent_payments.map(p=><tr key={p.id}><td>#{p.id}</td><td>{p.customer_name}</td><td>{money(p.amount)}</td><td>{p.payment_method}</td></tr>)}</tbody></table></div></div></div>
 </div>
}
